### ISSUE TITLE
interactive particle editor - animated particle

### ISSUE THREAD

**Issue by klaun76** [pixijs/pixi-particles#32]
Hi 

I'm not sure if this is right place to post but anyway. I would like to ask if there is possibility to update 
interactive particle editor so it can use AnimatedParticle. Our artist does a lot of testing in this editor, and it would be better if he could see result in real view. It would be acceptable even pass additional parameters as url parameter if you would not have time to update user interface. If i understand correctly only (or at least) framerate and loop parameter are needed to be configured, specially for animated particle.

cheers

.mrtn

**Comment by andrewstart** [comment]
I suppose a better place for this issue would be on the repo for the editor itself. Regardless, the reason the editor doesn't use it yet is because setting up a UI for handling a group of textures is more complicated, because I would need to handle both many images at once and spritesheets, if I were to do it properly.

**Comment by klaun76** [comment]
Thanks for an answer
