### ISSUE TITLE
The look of the particles has gotten a lot worse in the latest versions

### ISSUE THREAD

**Issue by mirraj2** [pixijs/pixi-particles#58]
See these two animated gifs for a comparison:

Good:
https://cl.ly/0T3m3S2o3t3D

Bad:
https://cl.ly/1G181J2x1z0Y

The first one is much brighter and has crisper edges.  The second one looks more dull and blurry.

**Steps for easy reproduction:**

```
{
	"alpha": {
		"start": 1,
		"end": 0
	},
	"scale": {
		"start": 0.4,
		"end": 0.4,
		"minimumScaleMultiplier": 10
	},
	"color": {
		"start": "#3be5ff",
		"end": "#3be5ff"
	},
	"speed": {
		"start": 10,
		"end": 10,
		"minimumSpeedMultiplier": 20
	},
	"acceleration": {
		"x": 0,
		"y": 0
	},
	"maxSpeed": 0,
	"startRotation": {
		"min": 0,
		"max": 360
	},
	"noRotation": false,
	"rotationSpeed": {
		"min": -1,
		"max": -1
	},
	"lifetime": {
		"min": 1,
		"max": 1
	},
	"blendMode": "screen",
	"frequency": 0.001,
	"emitterLifetime": -1,
	"maxParticles": 10000,
	"pos": {
		"x": 0,
		"y": 0
	},
	"addAtBack": false,
	"spawnType": "point"
}
```

Go to http://pixijs.github.io/pixi-particles-editor/ and load the above json into the editor.

Compare that to the latest version of pixi & latest version of pixi-particles that I have running at:  http://playglitter.com/particles

**Comment by andrewstart** [comment]
My understanding of the problem is that the blend mode is acting a little differently, resulting in PIXI 3.X making this particle setup look more energy-like, while 4.5.3 is making it look more smoke-like? We don't have any special rendering, we just use PIXI's regular sprite rendering - it's possible that a blend mode calculation was changed between versions. In fact, it looks like the new/bad version when I switch the rendering from WebGL to Canvas, so perhaps 3.X had an incorrect "screen" blend mode? Do the particles look correct if you use a different blend mode, like "add"?

**Comment by mirraj2** [comment]
Thank you!!!  When I switched it to "add", it looks like "screen" does in the PixiParticlesEditor.  They must have had a bug where both "screen" and "add" acted like "add" in 3.X
