### ISSUE TITLE
Independent Ticker?

### ISSUE THREAD

**Issue by gregmax17** [pixijs/pixi-particles#72]
Right now the particles can run via shared ticker, or manually. Is there a way to make them run independently? I'm in a situation where I have the game uses the shared ticker (animated sprites, some particle effects, etc), and when I go to the pause menu I have to pause the shared ticker but I still have particles in that. 

Should I just make another ticker specifically for the particles? I think it would be nice if it had one internally, or at least use that internal one. Or maybe ignore the speed of the shared ticker? 

Thoughts?

**Comment by andrewstart** [comment]
You will want to make another ticker just for the UI particles, so you can run those while the main game is paused. I am not particularly inclined to add in an internal ticker due to the infinite variety of people's ticker needs and implementations. Requiring an update method to be called results in the simplest way for allowing full control.
